name: Test

on:
  workflow_dispatch:
    inputs:
      foo:
        type: string
        description: Some random input

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.foo }}"
